name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Setup Mono
      uses: gabrielweyer/setup-mono@v1
      with:
        mono-version: latest
    - name: Setup NuGet CLI
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'
    - name: Create package
      run: nuget pack src/Monaco.Template.nuspec -OutputDirectory .
    - name: Push to NuGet
      run: dotnet nuget push "Monaco.Template.*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
