name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Setup Nuget
      uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{secrets.nuget_api_key}}
    - name: Create package
      run: nuget pack src/Monaco.Template.nuspec -OutputDirectory .
    - name: Push to NuGet
      run: nuget push "Monaco.Template.*.nupkg"
